# Generated by Django 4.0.3 on 2022-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('positivos', models.IntegerField()),
                ('negativos', models.IntegerField()),
            ],
        ),
    ]
