# Generated by Django 4.0.3 on 2022-05-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimientosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('totalMensajes', models.IntegerField()),
                ('positivos', models.IntegerField()),
                ('negativos', models.IntegerField()),
                ('neutrales', models.IntegerField()),
            ],
        ),
    ]
